
set nocompatible

" bootstrap pathogen & submodules
runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype plugin on

" moving around, searching and patterns
set incsearch
set ignorecase
set smartcase

" displaying text
set scrolloff=2
set number
set fillchars=vert:\ 

" make tabs visible
set list
set listchars=tab:»\  

" syntax, highlighting and spelling
syntax on
colorscheme molokai
set hlsearch
set cursorline

" multiple windows
set laststatus=2
set hidden

" terminal
set title
set ttyfast
set guicursor+=a:blinkon0-block-Cursor

" GUI
set guioptions-=T
set guifont=DejaVu\ Sans\ Mono\ 10
set guiheadroom=0

" messages and info
set ruler
set showcmd

" editing text
set backspace=indent,eol,start

" mapping
let mapleader = " "
noremap <leader><space> :noh<CR>
noremap <leader>n :NERDTreeToggle<CR>
noremap <leader>b :buffers<CR>:buffer<space>
noremap <leader>h 0
noremap <leader>l $
noremap ; :

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" the swap file
set directory=$HOME/.vim/swaps//

" command line editing
set wildmenu
set wildmode=longest:full

" etc
let g:netrw_liststyle = 3

