[ -z "$PS1" ] && return

export PS1="\u@\h \w> "

if [ -d "$HOME/local/bin" ]; then
       export PATH=$PATH:$HOME/local/bin
fi
if [ -d "$HOME/local/lib" ]; then
       export LD_LIBRARY_PATH=$HOME/local/lib
fi

setterm -blength 0

# allow continue suspended output with any key
stty ixany

alias ls='ls --color=auto'
alias l='less -S'
alias ll='ls -lh'
alias ld='ll -d */'
alias la='ll -A'
alias df='df -hTP'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'

[ -x /usr/bin/lesspipe.sh ] && eval "$(lesspipe.sh)"
[ -x "$(which dircolors)" ] && eval "`dircolors -b`"

export EDITOR='vim'

# prevent shell from exiting with Ctrl-d
IGNOREEOF=10


export HISTCONTROL=ignoredups

