[ -z "$PS1" ] && return

export PS1='\u@\h \W\$ '

if [ -d "$HOME/local/bin" ]; then
       export PATH=$HOME/local/bin:$PATH
fi

setterm -blength 0

# disable flow control
stty ixoff -ixon
stty stop undef
stty start undef

alias ls='ls --color=auto'
alias l='less -S'
alias ll='ls -lh'
alias ld='ll -d */'
alias la='ll -A'
alias df='df -hTP | column -t'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'

[ -x /usr/bin/lesspipe.sh ] && eval "$(lesspipe.sh)"
[ -x "$(which dircolors)" ] && eval "`dircolors -b`"

export EDITOR='vim'

# prevent shell from exiting with Ctrl-d
IGNOREEOF=10


export HISTCONTROL=ignoredups

